<?php

declare(strict_types=1);

namespace Lift\Routing;

use Lift\Container\Container;
use Lift\Exception\MethodNotAllowedException;
use Lift\Exception\NotFoundException;
use Lift\Http\Request;
use Lift\Http\Response;
use Lift\Pipeline\Pipeline;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\MiddlewareInterface;
use ReflectionFunction;
use ReflectionMethod;

/**
 * HTTP router — matches incoming requests to registered route handlers.
 *
 * Supports:
 * - Static and parameterised paths: `/users/{id:\d+}`
 * - Route groups with shared prefix and middleware
 * - Named routes for URL generation
 * - Any callable, `[Controller::class, 'method']`, or invokable class as handler
 * - Automatic 405 detection when the path exists but the method does not
 * - Handler return-value normalisation (array→JSON, string→HTML, null→204)
 */
final class Router
{
    /** @var Route[] Dynamic (parameterised) routes. */
    private array $routes = [];

    /**
     * Static fast-path: method → path → Route.
     *
     * Routes with no `{param}` placeholders are indexed here for O(1) dispatch.
     * Dynamic routes remain in $routes for the linear regex scan.
     *
     * @var array<string, array<string, Route>>
     */
    private array $static = [];

    /**
     * Reverse index for 405 detection on static routes: path → allowed methods.
     *
     * @var array<string, list<string>>
     */
    private array $staticPathMethods = [];

    /**
     * Named-route index: name → Route (populated lazily on first url() call).
     *
     * @var array<string, Route>|null  null means "not yet built"
     */
    private ?array $namedRoutes = null;

    /**
     * Per-process reflection cache for route handlers.
     * Key format: "ClassName::method" or closure identity.
     *
     * @var array<string, \ReflectionFunctionAbstract>
     */
    private static array $handlerReflectionCache = [];

    public function __construct(private readonly Container $container) {}

    // -----------------------------------------------------------------
    // Route registration
    // -----------------------------------------------------------------

    /**
     * @param string|string[] $methods
     */
    public function add(string|array $methods, string $path, mixed $handler): Route
    {
        $normalised = '/' . ltrim($path, '/');
        $route = new Route(
            methods: array_map('strtoupper', (array) $methods),
            path: $normalised,
            handler: $handler,
        );

        if (!str_contains($normalised, '{')) {
            foreach ($route->getMethods() as $m) {
                $this->static[$m][$normalised] = $route;
                $this->staticPathMethods[$normalised][] = $m;
            }
        } else {
            $this->routes[] = $route;
        }

        $this->namedRoutes = null; // invalidate named-route cache

        return $route;
    }

    public function group(string $prefix, callable $callback): RouteGroup
    {
        return new RouteGroup($prefix, $this, $callback);
    }

    // -----------------------------------------------------------------
    // Route cache — write / load
    // -----------------------------------------------------------------

    /**
     * Serialise all cacheable routes to a PHP file that opcache will compile.
     *
     * Closure handlers are silently skipped — use `[ClassName::class, 'method']`
     * style handlers when route caching is required.
     *
     * Typical usage:
     * ```php
     * // After registering all routes (e.g. at end of routes.php):
     * if ($env === 'production') {
     *     $router->writeCache(storage_path('routes.cache.php'));
     * }
     * ```
     *
     * @param string $file Absolute path for the generated PHP cache file.
     * @return int         Number of routes written (closure routes are excluded).
     * @throws \RuntimeException When the file cannot be written.
     */
    public function writeCache(string $file): int
    {
        $static  = [];
        $dynamic = [];

        foreach ($this->getRoutes() as $route) {
            $data = $route->toCacheable();
            if ($data === null) {
                continue;
            }
            if (!str_contains($data['path'], '{')) {
                foreach ($data['methods'] as $m) {
                    $static[$m][$data['path']] = $data;
                }
            } else {
                $dynamic[] = $data;
            }
        }

        $count   = count($dynamic) + array_sum(array_map('count', $static));
        $export  = var_export(['static' => $static, 'dynamic' => $dynamic], true);
        $content = "<?php\ndeclare(strict_types=1);\n// Generated by Lift Router — do not edit.\nreturn {$export};\n";

        $dir = dirname($file);
        if (!is_dir($dir) && !mkdir($dir, 0755, true) && !is_dir($dir)) {
            throw new \RuntimeException("Cannot create route cache directory: [{$dir}]");
        }

        if (file_put_contents($file, $content, LOCK_EX) === false) {
            throw new \RuntimeException("Cannot write route cache file: [{$file}]");
        }

        return $count;
    }

    /**
     * Load routes from a cache file previously written by {@see writeCache()}.
     *
     * Returns false when the file does not exist (first request / cache cleared).
     * When true is returned, route registration can be skipped for this request.
     *
     * Typical usage:
     * ```php
     * if (!$router->loadCache(storage_path('routes.cache.php'))) {
     *     require base_path('routes/web.php');
     *     $router->writeCache(storage_path('routes.cache.php'));
     * }
     * ```
     */
    public function loadCache(string $file): bool
    {
        if (!is_file($file)) {
            return false;
        }

        $data = require $file;

        if (!is_array($data) || (!isset($data['static']) && !isset($data['dynamic']))) {
            return false;
        }

        foreach ($data['static'] ?? [] as $method => $paths) {
            foreach ($paths as $path => $routeData) {
                if (isset($this->static[$method][$path])) {
                    continue; // already registered (mixed cache+live scenario)
                }
                $route = Route::fromCacheable($routeData);
                $this->static[$method][$path] = $route;
                $this->staticPathMethods[$path][] = $method;
            }
        }

        foreach ($data['dynamic'] ?? [] as $routeData) {
            $this->routes[] = Route::fromCacheable($routeData);
        }

        $this->namedRoutes = null;

        return true;
    }

    // -----------------------------------------------------------------
    // URL generation
    // -----------------------------------------------------------------

    public function url(string $name, array $params = []): string
    {
        if ($this->namedRoutes === null) {
            $this->namedRoutes = [];
            foreach ($this->allRoutes() as $route) {
                if ($route->getName() !== null) {
                    $this->namedRoutes[$route->getName()] = $route;
                }
            }
        }

        if (!isset($this->namedRoutes[$name])) {
            throw new \RuntimeException("Named route [{$name}] not found");
        }

        $url = $this->namedRoutes[$name]->getPath();
        foreach ($params as $key => $value) {
            $url = (string) preg_replace('/\{' . $key . '(?::[^}]+)?\}/', (string) $value, $url);
        }
        return $url;
    }

    /**
     * Return all registered routes (without duplicates).
     *
     * @return Route[]
     */
    public function getRoutes(): array
    {
        $routes = [];
        $seen   = [];
        foreach ($this->static as $paths) {
            foreach ($paths as $route) {
                $id = spl_object_id($route);
                if (!isset($seen[$id])) {
                    $seen[$id]  = true;
                    $routes[]   = $route;
                }
            }
        }
        foreach ($this->routes as $route) {
            $routes[] = $route;
        }
        return $routes;
    }

    /** Iterate all routes (static index + dynamic list) without duplicates. */
    private function allRoutes(): \Generator
    {
        $seen = [];
        foreach ($this->static as $paths) {
            foreach ($paths as $route) {
                $id = spl_object_id($route);
                if (!isset($seen[$id])) {
                    $seen[$id] = true;
                    yield $route;
                }
            }
        }
        foreach ($this->routes as $route) {
            yield $route;
        }
    }

    // -----------------------------------------------------------------
    // Dispatch
    // -----------------------------------------------------------------

    /**
     * @param array<MiddlewareInterface|string> $globalMiddleware
     */
    public function dispatch(Request $request, array $globalMiddleware = []): Response
    {
        $method = $request->getMethod();
        $path   = '/' . ltrim($request->getUri()->getPath(), '/');

        // O(1) static fast-path — no regex needed for exact-path routes.
        if (isset($this->static[$method][$path])) {
            $route = $this->static[$method][$path];
            // Static routes have no params — skip the Request clone withRouteParams([]).
            return $this->runThroughPipeline($route, $request, $globalMiddleware);
        }

        $matched          = null;
        // O(1) 405 check on static routes via the reverse path-methods index.
        $methodNotAllowed = isset($this->staticPathMethods[$path]);

        foreach ($this->routes as $route) {
            $params = $route->matches($method, $path);
            if ($params !== false) {
                $matched = [$route, $params];
                break;
            }
            if (!$methodNotAllowed && $route->pathMatches($path)) {
                $methodNotAllowed = true;
            }
        }

        if ($matched === null) {
            throw $methodNotAllowed
                ? new MethodNotAllowedException("Method {$method} not allowed for {$path}")
                : new NotFoundException("No route matched: {$path}");
        }

        [$route, $params] = $matched;
        $request = $request->withRouteParams($params);

        return $this->runThroughPipeline($route, $request, $globalMiddleware);
    }

    /** @param array<MiddlewareInterface|string> $globalMiddleware */
    private function runThroughPipeline(Route $route, Request $request, array $globalMiddleware): Response
    {
        $routeMiddleware = $route->getMiddleware();
        $middleware      = $globalMiddleware === [] ? $routeMiddleware : [...$globalMiddleware, ...$routeMiddleware];

        // Fast-path: skip Pipeline object allocation entirely when there is no middleware.
        if ($middleware === []) {
            return $this->callHandler($route->getHandler(), $request);
        }

        $pipeline = new Pipeline($this->container);
        return $pipeline->run(
            $request,
            $middleware,
            fn(ServerRequestInterface $req): Response => $this->callHandler(
                $route->getHandler(),
                $req instanceof Request ? $req : $request,
            ),
        );
    }

    // -----------------------------------------------------------------
    // Handler invocation
    // -----------------------------------------------------------------

    /**
     * Invoke a route handler.
     *
     * @param mixed $handler
     * @param Request $request
     * @return Response
     * @throws \ReflectionException
     */
    private function callHandler(mixed $handler, Request $request): Response
    {
        $overrides = ['request' => $request, 'req' => $request];

        if (is_array($handler) && count($handler) === 2) {
            [$class, $method] = $handler;
            $instance = is_object($class) ? $class : $this->container->make($class);
            $className = get_class($instance);
            $cacheKey  = $className . '::' . $method;
            $ref = self::$handlerReflectionCache[$cacheKey]
                ??= new ReflectionMethod($instance, $method);
            $args   = $this->container->resolveParameters($ref->getParameters(), $overrides);
            $result = $instance->{$method}(...$args);
        } elseif (is_callable($handler)) {
            if ($handler instanceof \Closure) {
                // Reflect the closure directly (no Closure::fromCallable wrapper).
                // Cache by file:line — stable across requests in persistent processes
                // (php -S, FPM workers) because the same source position → same signature.
                $ref      = new ReflectionFunction($handler);
                $cacheKey = ($ref->getFileName() ?: '') . ':' . $ref->getStartLine();
                $ref      = self::$handlerReflectionCache[$cacheKey] ??= $ref;
            } else {
                $closure  = \Closure::fromCallable($handler);
                $ref      = new ReflectionFunction($closure);
                $cacheKey = $ref->getName();
                $ref      = self::$handlerReflectionCache[$cacheKey] ??= $ref;
            }
            $args   = $this->container->resolveParameters($ref->getParameters(), $overrides);
            $result = $handler(...$args);
        } elseif (is_string($handler) && class_exists($handler)) {
            $instance = $this->container->make($handler);
            $cacheKey = $handler . '::__invoke';
            $ref  = self::$handlerReflectionCache[$cacheKey]
                ??= new ReflectionMethod($instance, '__invoke');
            $args   = $this->container->resolveParameters($ref->getParameters(), $overrides);
            $result = $instance(...$args);
        } else {
            throw new \InvalidArgumentException('Invalid route handler');
        }

        return $this->normalizeResponse($result);
    }

    /**
     * Normalize a handler result to a Response.
     *
     * @param mixed $result
     * @return Response
     */
    private function normalizeResponse(mixed $result): Response
    {
        return match (true) {
            $result instanceof Response         => $result,
            is_array($result), is_object($result) => Response::json($result),
            is_string($result)                  => Response::html($result),
            $result === null                    => Response::noContent(),
            default                             => Response::text((string) $result),
        };
    }
}
